#!/usr/bin/env bash

GREEN=$(tput setaf 2)
RED=$(tput setaf 1)
NC=$(tput sgr0)

if [ "$#" -eq "0" ]
then
	printf "[${RED}\u2717${NC}] Please enter a project directory to test with.\n"
	exit 1
fi

# generate a makefile for the binary executable on the test dir
python makepy.py test_binary $1

# compile the test files
cd $1 && make

if [ "$?" -eq "0" ]
then
	# no error occurred; all tests passed
	printf "\n[${GREEN}\u2713${NC}] Build test passed.\n"
	else
		printf "\n[${RED}\u2717${NC}] An error occurred.\n"
fi

# clean up test folder
make clean > /dev/null
rm Makefile
if [ "$?" -eq "0" ]
then
	printf "[${GREEN}\u2713${NC}] Build files cleaned.\n"
	else
		printf "[${RED}\u2717${NC}] Error removing build files.\n"
fi
