name: MakePy Build Test

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with: 
        fetch-depth: 1
    - name: Build/Run Makefile
    run: ./run_tests.sh tests/
